# Generated by Django 5.0.4 on 2024-05-10 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userinfo",
            options={"verbose_name": "用户表", "verbose_name_plural": "用户表"},
        ),
    ]
