# Generated by Django 5.0.4 on 2024-05-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="categroy",
            field=models.CharField(
                choices=[
                    ("Backend", "后端"),
                    ("Frontend", "前端"),
                    ("Lifestyle", "生活"),
                ],
                default="Backend",
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
