# Generated by Django 5.0.4 on 2024-05-16 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_post_categroy_delete_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="categroy",
            new_name="category",
        ),
    ]
